[package]
name = "rust-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="blog"
path="src/lib.rs"

[[bin]]
name="publish"
path="src/main.rs"

[dependencies]
